create table if not exists public.availability_cache (
  venue_id text primary key,
  received_at timestamptz not null default now(),
  payload jsonb not null
);

alter table public.availability_cache enable row level security;

create table if not exists public.planner_events (
  event_token text primary key,
  name text not null,
  date_start date not null,
  date_end date not null,
  preferred_start_time text not null,
  preferred_end_time text not null,
  minimum_duration_minutes integer not null default 60,
  created_at timestamptz not null default now()
);

create table if not exists public.planner_event_venues (
  event_token text not null references public.planner_events(event_token) on delete cascade,
  venue_id text not null,
  primary key (event_token, venue_id)
);

create table if not exists public.planner_participants (
  participant_id text primary key,
  event_token text not null references public.planner_events(event_token) on delete cascade,
  display_name text not null,
  display_name_key text,
  edit_token text not null,
  edit_password_hash text,
  created_at timestamptz not null default now(),
  unique (event_token, edit_token)
);

create table if not exists public.planner_availability_blocks (
  id bigint generated by default as identity primary key,
  event_token text not null references public.planner_events(event_token) on delete cascade,
  participant_id text not null references public.planner_participants(participant_id) on delete cascade,
  date date not null,
  start_minute integer not null,
  end_minute integer not null,
  check (start_minute >= 0 and start_minute < end_minute and end_minute <= 1440)
);

create index if not exists planner_participants_event_token_idx
  on public.planner_participants(event_token);

alter table public.planner_participants
  add column if not exists display_name_key text;

alter table public.planner_participants
  add column if not exists edit_password_hash text;

with ranked_names as (
  select
    participant_id,
    lower(regexp_replace(btrim(display_name), '[[:space:]]+', ' ', 'g')) as normalized_name,
    row_number() over (
      partition by event_token, lower(regexp_replace(btrim(display_name), '[[:space:]]+', ' ', 'g'))
      order by created_at, participant_id
    ) as name_rank
  from public.planner_participants
)
update public.planner_participants as participant
set display_name_key = case
  when ranked_names.name_rank = 1 then ranked_names.normalized_name
  else null
end
from ranked_names
where participant.participant_id = ranked_names.participant_id;

create unique index if not exists planner_participants_event_display_name_key_idx
  on public.planner_participants(event_token, display_name_key)
  where display_name_key is not null;

create index if not exists planner_availability_blocks_event_token_idx
  on public.planner_availability_blocks(event_token);

create index if not exists planner_availability_blocks_participant_id_idx
  on public.planner_availability_blocks(participant_id);

alter table public.planner_events enable row level security;
alter table public.planner_event_venues enable row level security;
alter table public.planner_participants enable row level security;
alter table public.planner_availability_blocks enable row level security;
